- name: enable ip forwarding
  ansible.builtin.command: sysctl -w net.inet.ip.forwarding=1 && sysctl -w net.inet6.ip6.forwarding=1
  notify:
    - apply changes to pf
    - enable pf at boot
    - restart the network service